---
- name: Delete ARO Cluster
  hosts: localhost
  connection: local
  
  collections:
    - community.kubernetes
  
  vars:
    aro_create: False

  vars_prompt:
    # - name: kubeconfig
    #   prompt: "Provide the full path to KUBECONFIG"
    #   private: no
    #   default: "{{ ansible_env.KUBECONFIG | default( lookup('env','HOME') + '/openshift/gcp/auth/kubeconfig') }}"

    - name: azure_profile
      prompt: "Azure profile to use(default: default)"
      private: no
      default: "default"

    - name: aro_location
      prompt: "Enter the Azure location to create the cluster (default: centralindia)"
      private: no
      default: "centralindia"

    - name: aro_cluster_name
      prompt: "Enter ARO cluster name"
      private: no
      default: "azr"

  environment:
    AZURE_PROFILE: "{{ azure_profile }}"
  #   K8S_AUTH_KUBECONFIG: "{{ kubeconfig }}"

  
  roles:
     - kameshsampath.aro
   # - kameshsampath.openshift_app_spices
